export * from './cards/CallWaiter'
export * from './cards/Categories'
export * from './cards/MainPlate'
export * from './cards/Plate'
export * from './cards/ModalPlate'
export * from './cards/ModalRequest'
export * from './forms/FormSearch'
export * from './loading/MainLoading'